version: '3'

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "443:443"
      - "80:80"
    tty: true
    restart: always
    volumes:
      - ./certs/:/var/lib/https-portal/
    environment:
      DOMAINS: >-
        chain-market.net -> http://web,
        chain.gives -> http://web
      STAGE: "production"
      CLIENT_MAX_BODY_SIZE: 100M
      # FORCE_RENEW: 'true'
    links:
      - web
    networks:
      -  chain_network
  web:
    container_name: web
    build: ./dockerbuild
    volumes:
      - .:/var/www
    restart: always
    networks:
      -  chain_network

networks:
  chain_network:
    ipam:
      config:
        - subnet: 172.25.0.0/24
